### ISSUE TITLE
Forward all

### ISSUE THREAD

**Issue by Ohmen** [h2non/toxy#52]
Hi,

is it posible proxy requests to all hosts and only poison specific routes?

```
proxy
  .forward('*')

proxy
  .forward('http://myhost')
  .get('/test')
  .poison(poisons.abort())
```

**Comment by tomas-fp** [comment]
Yes, please, see this example: https://github.com/h2non/toxy/blob/master/examples/routes.js

**Comment by dggriffin** [comment]
@tomas-fp, in your example, aren't you forwarding everything to 'http://httpbin.org'? Ohmen is asking if you can request to _all hosts._

**Comment by h2non** [comment]
You can do that by registering your custom middleware and a custom rule that only activates a some traffic poisoning selectively. E.g:
```js
proxy
  .use(defineHostTargetMiddleware)
  .poison(anEvilPoison)
  .withRule(filterByHost)
```

**Comment by dggriffin** [comment]
@h2non I see, could you elaborate on what we be included within `defineHostTargetMiddleware`?

With the below code, I'm trying to position toxy as a middleman to inject poison into any request made to it, rather than force requests to a specific forwarding host.

```
proxy.use(function(req, res, next) {
    next();
})
.poison(poisons.abort())
.withRule(toxy.rules.probability(50));

 proxy.all('/*');

 proxy.listen(3000);
```

Any guidance would be great!
