### ISSUE TITLE
MaxListenersExceededWarning when trying to update poison on the proxy

### ISSUE THREAD

**Issue by ost12666** [h2non/toxy#53]
Hi,

I am using the proxy for video player testing, switching network conditions within the playback session. I do this every time I want to change the network:

    if (poison) {
        proxy.remove(poison);
        poison = null;
    }

    poison = poisons.throttle({ chunk: chunkSize, threshold: chunkDelay});
    proxy.poison(poison);

And then I get this warning:

(node:19805) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit

I did a separate test program and the warning did not appear when just switching poisons but rather it appeared when the proxy was also requests on the same time.

Is there a better way to change the network bandwidth in the same session?

Thanks

**Comment by ost12666** [comment]
Does 'enhancement' means that changing the bandwidth is not currently possible? Is there a workaround?

**Comment by ost12666** [comment]
One suggestion: I currently use linux tc to condition the network. In order to atomically change the conditions I use replace so the connection will not go to normal between changes. So a replace poison method is probably required instead of removing and setting a new one.

**Comment by h2non** [comment]
Please, try upgrading `toxy` to `v0.3.14`:
```bash
$ npm update toxy
```

I have tried to reproduced your issue with this simple snippet, and it worked well for me:
```js
const toxy = require('..')

const proxy = toxy()
const rules = proxy.rules
const poisons = proxy.poisons

const createPoison = () => poisons.throttle({ chunk: 10, threshold: 100 })

// Create throttle poison
var poison = createPoison()

proxy
  .forward('http://httpbin.org')
  .withRule(rules.method('GET'))
  .withRule(rules.probability(90))

setInterval(() => {
  console.log('Replacing poisong...')
  proxy.remove(poison)
  poison = createPoison()
}, 1000)

proxy.all('/*')

proxy.listen(3000)
console.log('Server listening on port:', 3000)
```

**Comment by h2non** [comment]
Sorry, there's an issue with the code. The idiomatic approach for removing poisons would be:
```
// Remove poison by name at proxy level
proxy.remove('throttle')
// Or remove all registered poisons at proxy level
proxy.flushPoisons()
```

Full example:
```js
const toxy = require('..')

const proxy = toxy()
const rules = proxy.rules
const poisons = proxy.poisons

const createPoison = () => poisons.throttle({ chunk: 1024, threshold: 10 })

// Configure proxy
proxy
  .forward('http://httpbin.org')
  .poison(createPoison())
  .withRule(rules.method('GET'))
  .withRule(rules.probability(90))

// Redefine poison every
setInterval(() => {
  console.log('Replacing poison...')
  // Remove by name
  proxy.remove('throttle')
  // Or alternatively remove all poisons
  proxy.flushPoisons()
  // Re-register poison with custom rules
  toxy.poison(createPoison())
    .withRule(rules.method('GET'))
    .withRule(rules.probability(90))
}, 1000)

proxy.all('/*')

proxy.listen(3000)
console.log('Server listening on port:', 3000)

```

**Comment by ost12666** [comment]
Thanks! proxy.flushPoisons() works.

So I guess you need to update the doc. As for my comment on atomic operations I guess it is not a program with node since its single threaded so if I remove and then set a new one then its good.

**Comment by h2non** [comment]
Yes, I have added an example file showing how to do this, but the API should be improved as well.
